#!/usr/bin/env python
import os
import subprocess
from pathlib import Path


def main():
    out = Path(os.environ['TASK_OUTPUT_REPLACE'])
    requirements = Path('requirements')
    subprocess.run(['pip-compile-multi'])
    for file in requirements.glob('*.txt'):
        to = out / file
        to.parent.mkdir(parents=True, exist_ok=True)
        print(f'mv {file} -> {out / file}')
        file.rename(to)


if __name__ == '__main__':
    main()
